<?php

namespace BW\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTypeRepository extends EntityRepository
{
}
