<?php

namespace BW\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {
    
    public function findNestedBy($left, $right) {
        $qb = $this->createQueryBuilder('p')
                ->innerJoin('p.category', 'c')
                ->innerJoin('p.route', 'r')
                ->innerJoin('p.lang', 'l')
                ->where('p.published = 1')
                ->andWhere('c.published = 1')
                ->andWhere('c.left >= :left')
                ->andWhere('c.left <= :right')
                ->setParameter('left', $left)
                ->setParameter('right', $right)
                ->orderBy('p.created', 'DESC')
            ;
        
        return $qb->getQuery()->getResult();
    }
    
}
