<?php

namespace BW\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostCustomFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCustomFieldRepository extends EntityRepository
{
}
