<?php

namespace BW\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReplenishmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplenishmentRepository extends EntityRepository
{
}