<?php

namespace BW\RouterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RouteRepository extends EntityRepository
{
    
    public function findRouteBy($query, $locale = NULL) {
        $qb = $this->createQueryBuilder('r')
                ->select('r')
                ->where('r.query = :query')
                ->setParameter('query', $query)
            ;
        
        if ($locale === NULL) {
            $qb
                    ->andWhere('r.lang IS NULL')
                ;
        } else {
            $qb
                    ->join('r.lang', 'l')
                    ->andWhere('l.sign = :locale')
                    ->setParameter('locale', $locale)
                ;
        }
        
        $qb->setMaxResults(1);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
