<?php

namespace BW\MenuBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{
    
//    public function findOrdered($criteria) {
//        
//        $qb = $this->createQueryBuilder('i');
//        $qb->innerJoin('i.menu', 'm');
//        $qb->orderBy('i.nesting', 'ASC');
//        $q = $qb->getQuery();
//
//        return $q->getResult();
//    }
}
